import { type InferPageType, loader } from 'fumadocs-core/source';
import * as LucideIcons from 'lucide-react';
import { createElement } from 'react';
// Note: blog import removed to avoid fumadocs flatMap error during build
// Blog data is now handled by blog-data.ts
import { author, category, changelog, docs, pages } from '../../.source';
import { docsI18nConfig } from './docs/i18n';

/**
 * Turn a content source into a unified interface
 * .source folder is generated by `fumadocs-mdx`
 *
 * https://fumadocs.dev/docs/headless/source-api
 */
export const source = loader({
  baseUrl: '/docs',
  source: docs as any,
  i18n: docsI18nConfig,
  icon(iconName) {
    if (!iconName) {
      return undefined;
    }

    const IconComponent = (LucideIcons as Record<string, any>)[iconName];
    if (IconComponent) {
      return createElement(IconComponent);
    }

    console.warn(`Icon not found: ${iconName}`);
    return undefined;
  },
});

/**
 * Changelog source
 */
export const changelogSource = loader({
  baseUrl: '/changelog',
  source: changelog as any,
});

/**
 * Pages source - simplified to avoid fumadocs internal processing issues
 */
export const pagesSource = {
  getPage(slugs: string[], locale?: string) {
    const slug = slugs[0];
    if (!pages || !Array.isArray(pages)) {
      return null;
    }

    // Find the page by slug
    const page = (pages as any[]).find((p: any) => {
      const filePath = p.info?.path?.replace('.mdx', '') || '';
      return filePath === slug;
    });

    if (!page) {
      return null;
    }

    return {
      slugs: [page.info?.path?.replace('.mdx', '') || ''],
      data: {
        title: page.data?.title,
        description: page.data?.description,
        date: page.data?.date,
        body: page.data?.body,
      },
      url: `/pages/${page.info?.path?.replace('.mdx', '').replace('.zh', '')}`,
    };
  },

  getPages(locale?: string) {
    if (!pages || !Array.isArray(pages)) {
      return [];
    }

    return (pages as any[])
      .filter((p: any) => {
        if (!locale) return true;
        const filePath = p.info?.path || '';
        const isLocalized =
          locale === 'zh'
            ? filePath.includes('.zh')
            : !filePath.includes('.zh');
        return isLocalized;
      })
      .map((p: any) => ({
        slugs: [p.info?.path?.replace('.mdx', '').replace('.zh', '') || ''],
        data: {
          title: p.data?.title,
          description: p.data?.description,
          date: p.data?.date,
          body: p.data?.body,
        },
        url: `/pages/${p.info?.path?.replace('.mdx', '').replace('.zh', '')}`,
      }));
  },
};

/**
 * Blog authors source - simplified for collections without i18n
 */
export const authorSource = {
  getPage(slugs: string[], locale?: string) {
    const slug = slugs[0];
    if (!author || !Array.isArray(author)) {
      return null;
    }

    // Try to find with locale suffix first if locale is provided
    if (locale) {
      const localizedSlug = `${slug}.${locale}`;
      const localizedAuthor = author.find((a) => {
        const filePath = a._file?.path?.replace('.mdx', '') || '';
        return filePath === localizedSlug;
      });
      if (localizedAuthor) {
        return {
          slugs: [localizedAuthor._file?.path?.replace('.mdx', '') || ''],
          data: {
            name: localizedAuthor.name,
            avatar: localizedAuthor.avatar,
            description: localizedAuthor.description,
            body: localizedAuthor.body,
          },
          url: `/author/${localizedAuthor._file?.path?.replace('.mdx', '').replace('.zh', '')}`,
        };
      }
    }

    // Fallback to non-localized version
    const foundAuthor = author.find((a) => {
      const filePath = a._file?.path?.replace('.mdx', '') || '';
      return filePath === slug;
    });

    if (!foundAuthor) {
      return null;
    }

    return {
      slugs: [foundAuthor._file?.path?.replace('.mdx', '') || ''],
      data: {
        name: foundAuthor.name,
        avatar: foundAuthor.avatar,
        description: foundAuthor.description,
        body: foundAuthor.body,
      },
      url: `/author/${foundAuthor._file?.path?.replace('.mdx', '').replace('.zh', '')}`,
    };
  },

  getPages(locale?: string) {
    if (!author || !Array.isArray(author)) {
      return [];
    }

    return author.map((a) => ({
      slugs: [a._file?.path?.replace('.mdx', '') || ''],
      data: {
        name: a.name,
        avatar: a.avatar,
        description: a.description,
        body: a.body,
      },
      url: `/author/${a._file?.path?.replace('.mdx', '').replace('.zh', '')}`,
    }));
  },
};

/**
 * Blog categories source - simplified for collections without i18n
 */
export const categorySource = {
  getPage(slugs: string[], locale?: string) {
    const slug = slugs[0];
    if (!category || !Array.isArray(category)) {
      return null;
    }

    // Try to find with locale suffix first if locale is provided
    if (locale) {
      const localizedSlug = `${slug}.${locale}`;
      const localizedCategory = category.find((c) => {
        const filePath = c._file?.path?.replace('.mdx', '') || '';
        return filePath === localizedSlug;
      });
      if (localizedCategory) {
        return {
          slugs: [localizedCategory._file?.path?.replace('.mdx', '') || ''],
          data: {
            name: localizedCategory.name,
            description: localizedCategory.description,
            body: localizedCategory.body,
          },
          url: `/category/${localizedCategory._file?.path?.replace('.mdx', '').replace('.zh', '')}`,
        };
      }
    }

    // Fallback to non-localized version
    const foundCategory = category.find((c) => {
      const filePath = c._file?.path?.replace('.mdx', '') || '';
      return filePath === slug;
    });

    if (!foundCategory) {
      return null;
    }

    return {
      slugs: [foundCategory._file?.path?.replace('.mdx', '') || ''],
      data: {
        name: foundCategory.name,
        description: foundCategory.description,
        body: foundCategory.body,
      },
      url: `/category/${foundCategory._file?.path?.replace('.mdx', '').replace('.zh', '')}`,
    };
  },

  getPages(locale?: string) {
    if (!category || !Array.isArray(category)) {
      return [];
    }

    return category
      .filter((c) => {
        if (!locale) return true;
        const filePath = c._file?.path || '';
        const isLocalized =
          locale === 'zh'
            ? filePath.includes('.zh')
            : !filePath.includes('.zh');
        return isLocalized;
      })
      .map((c) => ({
        slugs: [c._file?.path?.replace('.mdx', '').replace('.zh', '') || ''],
        data: {
          name: c.name,
          description: c.description,
          body: c.body,
        },
        url: `/category/${c._file?.path?.replace('.mdx', '').replace('.zh', '')}`,
      }));
  },
};

/**
 * Blog source is now handled by blog-data.ts to avoid fumadocs build issues
 * See: src/lib/blog-data.ts
 */

// BlogType export for backward compatibility with components
export type BlogType = {
  slugs: string[];
  data: {
    title?: string;
    description?: string;
    date?: string;
    author?: string;
    categories?: string[];
    image?: string;
    published?: boolean;
    body?: any;
  };
  url: string;
};

export type ChangelogType = InferPageType<typeof changelogSource>;
export type PagesType = ReturnType<typeof pagesSource.getPage>;
export type AuthorType = ReturnType<typeof authorSource.getPage>;
export type CategoryType = ReturnType<typeof categorySource.getPage>;
