// Auto-generated by fumadocs-mdx
import type { InferMetaType, InferPageType } from 'fumadocs-core/source';

// Export empty arrays as fallback for collections
export const docs: any[] = [];
export const changelog: any[] = [];
export const pages: any[] = [];
export const author: any[] = [];
export const category: any[] = [];
export const blog: any[] = [];

// Types
export type Page = InferPageType<any>;
export type Meta = InferMetaType<any>;